# Executes a tool call request

uint8 TYPE_FUNCTION=1
uint8 type              # Tool type

string name             # Tool name

string parameters       # Tool parameters as JSON string
---
string parameters       # Tool output as JSON string